### ISSUE TITLE
Remove @babel/generator from peerDependencies

### ISSUE THREAD

**Issue by futagoza** [dosentmatter/babel-plugin-const-enum#7]
`@babel/generator` is installed with `@babel/core`, so also including this as a requirement in `peerDependencies` is just throwing an annoying warning, especially when I prefer only listing dependencies in my `package.json` that I use directly. I know it's a small and petty reason, but would you consider removing this from the `peerDependencies`?

**Comment by dosentmatter** [comment]
@futagoza, good suggestion. I will remove it when I have time. You are welcome to send in a PR.

**Comment by dosentmatter** [comment]
@futagoza, I published version 0.0.4 to npm.
