### ISSUE TITLE
Syntax error on react-native despite overrides workaround

### ISSUE THREAD

**Issue by luisnaranjo733** [dosentmatter/babel-plugin-const-enum#8]
I am seeing a SyntaxError when trying to use this babel plugin. I followed the instructions in the troubleshooting guide but the plugin is still failing on some react-native flow files.

The error I'm seeing when I run jest (with babel-jest)

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\node_modules\react-native\Libraries\Utilities\warnOnce.js:5
    var warnedKeys: {
                  ^

    SyntaxError: Unexpected token :

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/react-native/Libraries/react-native/react-native-implementation.js:5:16)
```

I can confirm that the [warnOnce.js](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/warnOnce.js) file that it is failing to parse is a RN flow file.

My babel.config.js
```
module.exports = {
  presets: ["module:metro-react-native-babel-preset", "@babel/preset-react", "@babel/preset-typescript"],
  plugins: [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "const-enum"
  ],
  overrides: [
    {
      test: /\.tsx?$/,
      plugins: [
        [
          'const-enum',
          {
            transform: 'removeConst',
          },
        ],
      ],
    },
  ],
}
```

**Comment by luisnaranjo733** [comment]
I have a repro project [here](https://github.com/luisnaranjo733/babel-plugin-const-enum-repro).

Steps I took to create the repro
1. npx react-native init ConstEnumRepro --template react-native-template-typescript
2. npm install
3. npm install --save-dev babel-plugin-const-enum
4. Add plugin to babel config
5. npm run test (this runs jest which uses babel-jest which uses babel under the hood)

Crash stack from repro (slightly different than the one I posted above, but seems to be same root cause of flow code blowing up this plugin)

Can confirm that [error-guard.js](https://github.com/facebook/react-native/blob/master/Libraries/polyfills/error-guard.js) is a RN flow file.

```
C:\code\ConstEnumRepro>npm run test

> ConstEnumRepro@0.0.1 test C:\code\ConstEnumRepro
> jest

 FAIL  __tests__/App-test.tsx
  ● Test suite failed to run

    SyntaxError: C:\code\ConstEnumRepro\node_modules\react-native\Libraries\polyfills\error-guard.js: Unexpected token, expected "," (51:22)

      49 |     _globalHandler && _globalHandler(error, true);
      50 |   },
    > 51 |   applyWithGuard<TArgs: $ReadOnlyArray<mixed>, TOut>(
         |                       ^
      52 |     fun: Fn<TArgs, TOut>,
      53 |     context?: ?mixed,
      54 |     args?: ?TArgs,

      at Object.raise (node_modules/@babel/parser/lib/index.js:6931:17)
      at Object.unexpected (node_modules/@babel/parser/lib/index.js:8324:16)
      at Object.expect (node_modules/@babel/parser/lib/index.js:8310:28)
      at Object.tsParseDelimitedListWorker (node_modules/@babel/parser/lib/index.js:4522:14)
      at Object.tsParseDelimitedList (node_modules/@babel/parser/lib/index.js:4494:25)
      at Object.tsParseBracketedList (node_modules/@babel/parser/lib/index.js:4540:25)
      at Object.tsParseTypeParameters (node_modules/@babel/parser/lib/index.js:4648:24)
      at Object.tsTryParseTypeParameters (node_modules/@babel/parser/lib/index.js:4635:19)
      at Object.parseObjPropValue (node_modules/@babel/parser/lib/index.js:6080:33)
      at Object.parseObjectMember (node_modules/@babel/parser/lib/index.js:9984:10)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.852s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ConstEnumRepro@0.0.1 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ConstEnumRepro@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jonaranj\AppData\Roaming\npm-cache\_logs\2019-11-05T19_28_20_781Z-debug.log```

**Comment by dosentmatter** [comment]
@luisnaranjo733
> I am seeing a SyntaxError when trying to use this babel plugin. I followed the instructions in the troubleshooting guide but the plugin is still failing on some react-native flow files.
> 
> The error I'm seeing when I run jest (with babel-jest)
> 
> 
> 
> ```
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\node_modules\react-native\Libraries\Utilities\warnOnce.js:5
>     var warnedKeys: {
>                   ^
> 
>     SyntaxError: Unexpected token :
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
>       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
>       at Object.<anonymous> (node_modules/react-native/Libraries/react-native/react-native-implementation.js:5:16)
> ```
> 
> I can confirm that the [warnOnce.js](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/warnOnce.js) file that it is failing to parse is a RN flow file.
> 
> My babel.config.js
> 
> 
> 
> ```
> module.exports = {
>   presets: ["module:metro-react-native-babel-preset", "@babel/preset-react", "@babel/preset-typescript"],
>   plugins: [
>     ["@babel/plugin-proposal-decorators", { "legacy": true }],
>     "const-enum"
>   ],
>   overrides: [
>     {
>       test: /\.tsx?$/,
>       plugins: [
>         [
>           'const-enum',
>           {
>             transform: 'removeConst',
>           },
>         ],
>       ],
>     },
>   ],
> }
> ```

Your babel config is wrong. You shouldn't have `const-enum` in the plugins array outside of overrides. The point of the overrides is to only run `const-enum` for ts or tsx files. If you have it in the global plugins, it will run for all files including flow .js files.

You said you followed the instructions on [https://github.com/dosentmatter/babel-plugin-const-enum#troubleshooting](troubleshooting), but please double-check and read it carefully. The troubleshooting guide suggests two methods - manual overrides or automatic overrides using my babel preset and not babel plugin. I'm not sure if you have tried out my preset. I suggest you use the babel preset unless you need to run this plugin on files other than ts or tsx.

**Comment by dosentmatter** [comment]
> I have a repro project [here](https://github.com/luisnaranjo733/babel-plugin-const-enum-repro).
> 
> Steps I took to create the repro
> 
> 1. npx react-native init ConstEnumRepro --template react-native-template-typescript
> 2. npm install
> 3. npm install --save-dev babel-plugin-const-enum
> 4. Add plugin to babel config
> 5. npm run test (this runs jest which uses babel-jest which uses babel under the hood)
> 
> Crash stack from repro (slightly different than the one I posted above, but seems to be same root cause of flow code blowing up this plugin)
> 
> Can confirm that [error-guard.js](https://github.com/facebook/react-native/blob/master/Libraries/polyfills/error-guard.js) is a RN flow file.
> 
> 
> 
> ```
> C:\code\ConstEnumRepro>npm run test
> 
> > ConstEnumRepro@0.0.1 test C:\code\ConstEnumRepro
> > jest
> 
>  FAIL  __tests__/App-test.tsx
>   ● Test suite failed to run
> 
>     SyntaxError: C:\code\ConstEnumRepro\node_modules\react-native\Libraries\polyfills\error-guard.js: Unexpected token, expected "," (51:22)
> 
>       49 |     _globalHandler && _globalHandler(error, true);
>       50 |   },
>     > 51 |   applyWithGuard<TArgs: $ReadOnlyArray<mixed>, TOut>(
>          |                       ^
>       52 |     fun: Fn<TArgs, TOut>,
>       53 |     context?: ?mixed,
>       54 |     args?: ?TArgs,
> 
>       at Object.raise (node_modules/@babel/parser/lib/index.js:6931:17)
>       at Object.unexpected (node_modules/@babel/parser/lib/index.js:8324:16)
>       at Object.expect (node_modules/@babel/parser/lib/index.js:8310:28)
>       at Object.tsParseDelimitedListWorker (node_modules/@babel/parser/lib/index.js:4522:14)
>       at Object.tsParseDelimitedList (node_modules/@babel/parser/lib/index.js:4494:25)
>       at Object.tsParseBracketedList (node_modules/@babel/parser/lib/index.js:4540:25)
>       at Object.tsParseTypeParameters (node_modules/@babel/parser/lib/index.js:4648:24)
>       at Object.tsTryParseTypeParameters (node_modules/@babel/parser/lib/index.js:4635:19)
>       at Object.parseObjPropValue (node_modules/@babel/parser/lib/index.js:6080:33)
>       at Object.parseObjectMember (node_modules/@babel/parser/lib/index.js:9984:10)
> 
> Test Suites: 1 failed, 1 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        0.852s
> Ran all test suites.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ConstEnumRepro@0.0.1 test: `jest`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ConstEnumRepro@0.0.1 test script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\jonaranj\AppData\Roaming\npm-cache\_logs\2019-11-05T19_28_20_781Z-debug.log```
> ```

Thanks for creating a repo for reproducing the issue. However, it seems to be incomplete. The babel config only has:
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ["const-enum"]
};
```

This doesn't match with the babel config you posted in your initial post, nor does it have overrides or the preset. After adding overrides or the preset, it works for me. So please double check that you are following the troubleshooting guide correctly. Let me know if you still have issues.

**Comment by dosentmatter** [comment]
@luisnaranjo733, any update? If not, I am going to close this issue.
